Feature/issue 71/employer profile page
COENS-SOENS/-COENS-SOENS-soen341project2023- pull request #92
Opened 2023-03-17 22:04 UTC by Firdaws-b

2023-03-17 22:04 UTC, fluffyCookie0 approved these changes

2023-03-17 23:31 UTC, BayanAlsalem approved these changes

2023-03-20 18:35 UTC, ItsDezi requested changes

2023-03-20 18:35 UTC, ItsDezi commented on web-client/src/pages/EmployerProfilePage.js
Is there any way to make it so that when a company name is updated, the company name on the job postings are updated too?

2023-03-20 19:07 UTC, Firdaws-b commented on web-client/src/pages/EmployerProfilePage.js
I noticed that yesterday. And yes, it's feasible I just need to listen for any changes done. 
I will take a look into that and fix the issue.

2023-03-20 19:29 UTC, ItsDezi commented on web-client/src/pages/EmployerProfilePage.js
Thank you!

2023-03-22 02:19 UTC, Firdaws-b commented on web-client/src/pages/EmployerProfilePage.js
issue fixed. Please refer to commit number bcbf74f

2023-03-23 22:49 UTC, ItsDezi commented on web-client/src/pages/EmployerProfilePage.js
I wasn't able to see the changes. Was it working for you? @Firdaws-b

2023-03-24 02:17 UTC, Firdaws-b commented on web-client/src/pages/EmployerProfilePage.js
I fixed the issue, please refer to commit 6e4ce48

2023-03-24 02:44 UTC, ItsDezi approved these changes

2023-03-24 03:21 UTC, merged