Feature/issue 65/admin page
COENS-SOENS/-COENS-SOENS-soen341project2023- pull request #95
Opened 2023-03-18 03:39 UTC by BayanAlsalem

2023-03-18 03:49 UTC, Firdaws-b approved these changes

2023-03-18 03:53 UTC, fluffyCookie0 approved these changes

2023-03-20 15:54 UTC, ItsDezi requested changes

2023-03-20 15:54 UTC, ItsDezi commented on web-client/src/pages/AdminProfile.js
Please fix routing to this page before merging

2023-03-20 15:54 UTC, ItsDezi commented on web-client/src/App.js
Please ensure you lint big files that many components rely on like this one.

2023-03-20 15:54 UTC, ItsDezi commented on web-client/src/Components/NavBars/AdminSideBar.js
Can you not reuse the existing sidebar class and just add another export?

2023-03-20 15:54 UTC, ItsDezi commented on web-client/src/pages/Home.js
after logging in as an admin, nothing appears on home page for me

2023-03-23 20:33 UTC, BayanAlsalem commented on web-client/src/pages/AdminProfile.js
done

2023-03-23 20:33 UTC, BayanAlsalem commented on web-client/src/pages/Home.js
issue fixed. Please refer to commit number c8d45b3

2023-03-23 21:33 UTC, BayanAlsalem commented on web-client/src/App.js
issue fixed. Please refer to commit number c8d45b3

2023-03-23 21:33 UTC, BayanAlsalem commented on web-client/src/Components/NavBars/AdminSideBar.js
I'll look at this in sprint 4

2023-03-23 22:22 UTC, ItsDezi commented on web-client/src/pages/Home.js
why was this happening? @BayanAlsalem

2023-03-23 22:26 UTC, ItsDezi requested changes

2023-03-23 22:26 UTC, ItsDezi commented on web-client/src/pages/jobPost.js
Should we leave these edits out. I made a lot of modifications to this page today regarding the editing feature and I feel like admins should also be able to edit/delete postings.

2023-03-24 02:56 UTC, ItsDezi approved these changes

2023-03-24 03:00 UTC, merged